services:
  # Backend API Service
  - name: sql-backend
    type: web
    env: node
    buildCommand: npm install
    startCommand: node server.js
    region: us-central
    branch: main
    plan: free
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_USER
        value: wings_cafe
      - key: DB_PASSWORD
        value: Rapelang03&&
      - key: DB_NAME
        value: wings_cafe
      - key: DB_PORT
        value: 3306

databases:
  # MySQL Database
  - name: sql-database
    type: mysql
    plan: free
    region: us-central
